apiVersion: v1
kind: PersistentVolume
metadata:
  name: mineops-minecraft-data
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: game-server
    app.kubernetes.io/part-of: mineops
    app.kubernetes.io/managed-by: manifest
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mineops-hostpath
  hostPath:
    path: /var/lib/rancher/k3s/storage/mineops-minecraft-data
    type: DirectoryOrCreate
