apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: mineops
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: game-server
    app.kubernetes.io/part-of: mineops
    app.kubernetes.io/managed-by: terraform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
