apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mineops-local
servers: 1
agents: 1
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6550"
ports:
  - port: 25565:25565
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${MINEOPS_STORAGE_PATH}:/var/lib/rancher/k3s/storage
    nodeFilters:
      - server:*
      - agent:*
  - volume: ${MINEOPS_BACKUP_HOST_PATH}:/backups
    nodeFilters:
      - server:*
      - agent:*
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
