apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discord-bot-readonly
  namespace: mineops
  labels:
    app.kubernetes.io/name: discord-bot
    app.kubernetes.io/component: chatops
    app.kubernetes.io/part-of: mineops
    app.kubernetes.io/managed-by: manifest
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - minecraft
    verbs:
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    resourceNames:
      - minecraft
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - get
      - create
