apiVersion: v1
kind: ServiceAccount
metadata:
  name: discord-bot
  namespace: mineops
  labels:
    app.kubernetes.io/name: discord-bot
    app.kubernetes.io/component: chatops
    app.kubernetes.io/part-of: mineops
    app.kubernetes.io/managed-by: manifest
