name: Terraform

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -recursive infra/terraform
